daemon = false
data_dir = "/home/.revault_coordinatord"
log_level = "trace"

postgres_uri = "postgresql://revault:revault@coordinator_db:5432/coordinator_db"

# Edit below
managers = []
stakeholders = []
watchtowers = []
